//
// Created by elektron on 26/03/18.
//

#ifndef TOURBILLONDELUMIERE_DEFINES_H
#define TOURBILLONDELUMIERE_DEFINES_H

#define PWM_FREQUENCY 20000

#define SERVO_SPEED 100
#define ANGLE_AX12_VERT 190
#define ANGLE_AX12_ORANGE 10
#define ANGLE_AX12_MID 105

#define PWM_TURBINE 200
#define PERCENT_MOTOR 40
#define PERCENT_MOTOR_BACK 40
#define PERCENT_MOTOR_COME_BACK 60

#define TENTATIVE_MAX 4

#endif //TOURBILLONDELUMIERE_DEFINES_H
