//
// Created by elektron on 26/03/18.
//

#ifndef TOURBILLONDELUMIERE_DEFINES_H
#define TOURBILLONDELUMIERE_DEFINES_H

#define PWM_FREQUENCY 20000

#define SERVO_SPEED 100
#define ANGLE_AX12_VERT 300
#define ANGLE_AX12_ORANGE 100
#define ANGLE_AX12_MID 195
#define TIME_TO_MOVE_AX12 11*SERVO_SPEED

#define PWM_TURBINE 200
#define PERCENT_MOTOR 60
#define PERCENT_MOTOR_BACK 40
#define PERCENT_MOTOR_COME_BACK 60

#define TENTATIVE_MAX 1

#endif //TOURBILLONDELUMIERE_DEFINES_H
